### ISSUE TITLE
refactor resizing api.

### ISSUE THREAD

**Issue by trebor** [twitter/d3kit#12]
have a look at the resize and auto resize options and see if the api can be simplified a little.

**Comment by trebor** [comment]
i propose to refactor the current resizing api from:

```
skeleton.resizeToFitContainer: resize to fit the skeleton's container.
skeleton.resizeToAspectRatio: resize to specified aspect ratio.
```

to:

```
skeleton.resize - immediately resize chart following rules as specified by autoResize() and autoResizeToAspectRatio().
```

this does limit functionality a little, bit, but i think it fits better with common use cases and is less confusing to new users.

**Comment by kristw** [comment]
I like the simplification, but specifying options via autoResize maybe less intuitive when I want to resize only once. How about grouping resize options together, which can be set via either `resize(resizeOptions)` or `autoResize(resizeOptions)`? 

Then, call `resize()` if you want to resize once, `autoResize()` for auto-detect. 

In `resizeOptions`
- auto:Boolean 
- side: 'width', 'height' or 'both'
- aspectRatio: null or some value

With this we can also implement autoResize by calling resize and set auto to true.

On second thought, what about renaming both to `fit()` and `autoFit()` rather than `resize()`?

**Comment by kristw** [comment]
Resolved in v3
